RELEASE_BUILD := 1

#-------------------------------------------------------------------------------
.SUFFIXES:
#-------------------------------------------------------------------------------

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment. export DEVKITPRO=<path to>/devkitpro")
endif

DEVKITPPC ?= $(DEVKITPRO)/devkitPPC

TOPDIR ?= $(CURDIR)

include $(DEVKITPPC)/wii_rules

#-------------------------------------------------------------------------------
# TARGET is the name of the output
# BUILD is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# DATA is a list of directories containing data files
# INCLUDES is a list of directories containing header files
#-------------------------------------------------------------------------------
TARGET		:=	re3
BUILD		:=	build_wii
SOURCES		:=	src \
				src/animation \
				src/audio \
				src/audio/oal \
				src/audio/eax \
				src/buildings \
				src/collision \
				src/control \
				src/core \
				src/entities \
				src/extras \
				src/fakerw \
				src/math \
				src/modelinfo \
				src/objects \
				src/peds \
				src/renderer \
				src/rw \
				src/save \
				src/skel \
				src/skel/wii \
				src/text \
				src/vehicles \
				src/weapons
DATA		:=	data
INCLUDES	:=	$(SOURCES) \
				vendor/librw \
				vendor/librw/inc \
				vendor/openal-soft/include \
				vendor/dr_libs

#-------------------------------------------------------------------------------
# options for code generation
#-------------------------------------------------------------------------------
CFLAGS	:=	-w -O2 -ffunction-sections \
			$(MACHDEP)

CFLAGS	+=	$(INCLUDE) -D__WII__ -DLIBRW -DAUDIO_OAL -DrwBIGENDIAN -DBIGENDIAN

CXXFLAGS	:= $(CFLAGS)

ASFLAGS	:=	$(MACHDEP)
LDFLAGS	=	$(MACHDEP) -Wl,-Map,$(notdir $*.map)

ifeq ($(RELEASE_BUILD), 0)
	CFLAGS += -g -D_DEBUG_BUILD_
	CXXFLAGS += -g -D_DEBUG_BUILD_
	ASFLAGS += -g
	LDFLAGS += -g
endif

LIBS	:= -lrw -lmpg123 -lopenal -lwiiuse -lbte -lfat -laesnd -logc -lm

#-------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level
# containing include and lib
#-------------------------------------------------------------------------------
LIBDIRS	:= $(PORTLIBS) $(TOPDIR)/vendor/librw $(TOPDIR)/vendor/openal-soft


#-------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#-------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#-------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(TARGET)
export TOPDIR	:=	$(CURDIR)

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir)) \
					$(foreach dir,$(DATA),$(CURDIR)/$(dir))

export DEPSDIR	:=	$(CURDIR)/$(BUILD)

CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
BINFILES	:=	$(foreach dir,$(DATA),$(notdir $(wildcard $(dir)/*.*)))

#-------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#-------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
#-------------------------------------------------------------------------------
	export LD	:=	$(CC)
#-------------------------------------------------------------------------------
else
#-------------------------------------------------------------------------------
	export LD	:=	$(CXX)
#-------------------------------------------------------------------------------
endif
#-------------------------------------------------------------------------------

export OFILES_BIN	:=	$(addsuffix .o,$(BINFILES))
export OFILES_SRC	:=	$(CPPFILES:.cpp=.o) $(CFILES:.c=.o)
export OFILES 		:=	$(OFILES_BIN) $(OFILES_SRC)
export HFILES_BIN	:=	$(addsuffix .h,$(subst .,_,$(BINFILES)))

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
					$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
					-I$(LIBOGC_INC) \
					-I$(CURDIR)/$(BUILD)

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib) \
					-L$(LIBOGC_LIB)

.PHONY: $(BUILD) clean vendor all

#-------------------------------------------------------------------------------
all: $(BUILD)

vendor:
	@echo Building librw
	@$(MAKE) --no-print-directory -C $(TOPDIR)/vendor/librw -f Makefile.wii
	@echo Building openal-soft
	@$(MAKE) --no-print-directory -C $(TOPDIR)/vendor/openal-soft -f Makefile.wii

$(BUILD): | vendor
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.wii

#-------------------------------------------------------------------------------
clean:
	@$(MAKE) --no-print-directory -C $(TOPDIR)/vendor/librw -f Makefile.wii clean
	@$(MAKE) --no-print-directory -C $(TOPDIR)/vendor/openal-soft -f Makefile.wii clean
	@echo clean ...
	@rm -fr $(BUILD) $(TARGET).dol $(TARGET).elf

#-------------------------------------------------------------------------------
else

DEPENDS	:=	$(OFILES:.o=.d)

#-------------------------------------------------------------------------------
# main targets
#-------------------------------------------------------------------------------
all	: $(OUTPUT).dol
	@mkdir -p $(TOPDIR)/apps/re3
	@cp $(OUTPUT).dol $(TOPDIR)/apps/re3/boot.dol

$(OUTPUT).dol	:	$(OUTPUT).elf
$(OUTPUT).elf	:	$(OFILES) $(TOPDIR)/vendor/librw/lib/librw.a $(TOPDIR)/vendor/openal-soft/lib/libopenal.a

$(OFILES_SRC)	: $(HFILES_BIN)

#-------------------------------------------------------------------------------
# you need a rule like this for each extension you use as binary data
#-------------------------------------------------------------------------------
%.bin.o	%_bin.h :	%.bin
#-------------------------------------------------------------------------------
	@echo $(notdir $<)
	@$(bin2o)

-include $(DEPENDS)

#-------------------------------------------------------------------------------
endif
#-------------------------------------------------------------------------------
